### ISSUE TITLE
Improvements and code quality

### ISSUE THREAD

**Issue by jthaman** [jthaman/consult-everything#1]
@minad, if you can take a look and offer some pointers, I would appreciate. The code for `consult-everything` is based on `consult-locate`.

**Comment by minad** [comment]
I am afraid I cannot help with respect to non-free operating systems, since I've not used them for years. As for the code quality, I think your package should be alright if you follow Consult itself and the other `consult-*` packages which are around. But note that Consult may have issues on Windows (search the Consult issue tracker). Some of these issues may have been sorted out, some others may not, but so far nobody stepped up providing better support. The root causes of the problems lay also in Emacs itself which only offers subpar support on Windows.

**Comment by jthaman** [comment]
Thanks, I'm well aware of the crappiness of using Emacs on windows, but it's still better than anything else :)
